#!/bin/bash

git config credential.https://github.com.zhangdongzhou zhangdongzhou
git init

cd python_ref_update
python reference_list.py
cd ..

git add --all
git commit -m "Publication Update"
git push -u origin master