#!/bin/bash

git config --global user.email "tochozhang@gmail.com"
git config --global user.name "zhangdongzhou"
git config --global credential.helper store
git init

cd python_ref_update
python reference_list.py
cd ..

git add --all
git commit -m "Publication Update"
git push -u origin master